CC = gcc

tweets_generator:  linked_list.c linked_list.h markov_chain.c markov_chain.h
	$(CC) tweets_generator.c  markov_chain.c linked_list.c -o tweets_generator

snakes_and_ladders:  linked_list.c linked_list.h markov_chain.c markov_chain.h
	$(CC) tweets_generator.c  markov_chain.c linked_list.c -o snakes_and_ladders